trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Azure Registry'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Azure Registry'
    repository: 'samplewebapp'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest